#!/bin/sh -e

# Capture all output to a log file
exec > /root/uci-defaults.log 2>&1

# Define variables

build_desc="Arcadyan AW1000 NSS|RMNET"

root_password="admin@aw1000"

hostname="Telstra5G"
description="Arcadyan AW1000 NSS|RMNET"

country="PH"
timezone="PST-8"
zonename="Asia/Manila"

port="/dev/ttyUSB2"
interface="5G"
apn="internet"

ap_5g_ssid="GodChryzWrt"
ap_2g_ssid="${ap_5g_ssid}"
ap_key="wireless123@GodChryzWrt"

ubuntu_sshkey="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6bCJ+pLxnl+Dze8NSc53iWfmxm/0ou352AdZjOBJFT godchryz"

# Configure default password
if [ -n "$root_password" ]; then
  (echo "$root_password"; sleep 1; echo "$root_password") | passwd > /dev/null
fi

# Add ssh keys
# Write SSH key files to /etc/dropbear/authorized_keys
echo "$ubuntu_sshkey" >> /etc/dropbear/authorized_keys

# Restart Dropbear SSH server
# /etc/init.d/dropbear restart

# Delete all pre-configured adblock-fast rules
while uci show adblock-fast | grep -q '@file_url'; do
    uci del adblock-fast.@file_url[-1]  
done

# Make the custom scripts executable
chmod +x /etc/init.d/custom_script
chmod +x /usr/bin/custom_script
chmod +x /usr/lib/custom_script/*.sh

uci -q batch <<- EOF > /dev/null

set system.@system[0]=system
set system.@system[0].hostname='${hostname}'
set system.@system[0].timezone='${timezone}'
set system.@system[0].zonename='${zonename}'
set system.@system[0].description='${description}'

set system.ntp=timeserver
set system.ntp.enable_server='1'
del system.ntp.server
add_list system.ntp.server='3.ph.pool.ntp.org'
add_list system.ntp.server='2.asia.pool.ntp.org'
add_list system.ntp.server='0.asia.pool.ntp.org'
add_list system.ntp.server='time.google.com'
add_list system.ntp.server='time.cloudflare.com'
set system.ntp.interface='lan'

add_list network.@device[-1].ports='wan'

del network.lan.ip6assign
set network.lan.delegate='0'

del network.wan
del network.wan6

set network.5G=interface
set network.5G.proto='quectel'
set network.5G.device='/dev/cdc-wdm0'
set network.5G.apn='${apn}'
set network.5G.auth='none'
set network.5G.pdptype='ipv4'
set network.5G.sourcefilter='0'
set network.5G.delegate='0'

set network.wwan=interface
set network.wwan.proto='dhcp'
set network.wwan.device='wwan0_1'
set network.wwan.delegate='0'
set network.wwan.hostname='*'

del dhcp.lan.dhcpv6
del dhcp.lan.ra
del dhcp.lan.ra_slaac
del dhcp.lan.ra_flags
del dhcp.lan.max_preferred_lifetime
del dhcp.lan.max_valid_lifetime

del firewall.@zone[1].network
add_list firewall.@zone[1].network='wwan'

set wireless.radio0=wifi-device
set wireless.radio0.type='mac80211'
set wireless.radio0.path='platform/soc@0/c000000.wifi'
set wireless.radio0.band='5g'
set wireless.radio0.channel='36'
set wireless.radio0.htmode='HE160'
set wireless.radio0.disabled='0'
set wireless.radio0.country='PH'
set wireless.radio0.cell_density='0'
set wireless.radio0.mu_beamformer='1'
set wireless.radio0.vendor_vht='1'
set wireless.default_radio0=wifi-iface
set wireless.default_radio0.device='radio0'
set wireless.default_radio0.network='lan'
set wireless.default_radio0.mode='ap'
set wireless.default_radio0.ssid='${ap_5g_ssid}'
set wireless.default_radio0.encryption='psk2'
set wireless.default_radio0.key='${ap_key}'

set wireless.radio1=wifi-device
set wireless.radio1.type='mac80211'
set wireless.radio1.path='platform/soc@0/c000000.wifi+1'
set wireless.radio1.band='2g'
set wireless.radio1.channel='1'
set wireless.radio1.htmode='HE20'
set wireless.radio1.disabled='0'
set wireless.radio1.country='PH'
set wireless.radio1.cell_density='0'
set wireless.radio1.mu_beamformer='1'
set wireless.radio1.vendor_vht='1'
set wireless.default_radio1=wifi-iface
set wireless.default_radio1.device='radio1'
set wireless.default_radio1.network='lan'
set wireless.default_radio1.mode='ap'
set wireless.default_radio1.ssid='${ap_2g_ssid}'
set wireless.default_radio1.encryption='psk2'
set wireless.default_radio1.key='${ap_key}'

set cpufreq.cpufreq=settings
set cpufreq.cpufreq.governor0='performance'
set cpufreq.cpufreq.minfreq0='1017600'
set cpufreq.cpufreq.maxfreq0='2208000'
set cpufreq.global=settings
set cpufreq.global.set='1'

set modemband.@modemband[0]=modemband
set modemband.@modemband[0].iface='${interface}'
set modemband.@modemband[0].wanrestart='1'
set modemband.@modemband[0].modemrestart='1'
set modemband.@modemband[0].notify='0'
set modemband.@modemband[0].restartcmd='AT+CFUN=1,1'
set modemband.@modemband[0].modemid='2c7c0800RG500Q-EA'
set modemband.@modemband[0].set_port='${port}'

set 3ginfo.@3ginfo[0]=3ginfo
set 3ginfo.@3ginfo[0].network='${interface}'
set 3ginfo.@3ginfo[0].device='${port}'

set sms_tool_js.@sms_tool_js[0]=sms_tool_js
set sms_tool_js.@sms_tool_js[0].storage='ME'sms-tool
set sms_tool_js.@sms_tool_js[0].mergesms='1'
set sms_tool_js.@sms_tool_js[0].pnumber='63'
set sms_tool_js.@sms_tool_js[0].prefix='1'
set sms_tool_js.@sms_tool_js[0].lednotify='1'
set sms_tool_js.@sms_tool_js[0].ussd='0'
set sms_tool_js.@sms_tool_js[0].pdu='0'
set sms_tool_js.@sms_tool_js[0].sendingroup='0'
set sms_tool_js.@sms_tool_js[0].information='1'
set sms_tool_js.@sms_tool_js[0].checktime='5'
set sms_tool_js.@sms_tool_js[0].prestart='4'
set sms_tool_js.@sms_tool_js[0].ledtype='D'
set sms_tool_js.@sms_tool_js[0].smsled='green:phone'
set sms_tool_js.@sms_tool_js[0].sms_count='0'
set sms_tool_js.@sms_tool_js[0].coding='auto'
set sms_tool_js.@sms_tool_js[0].algorithm='Advanced'
set sms_tool_js.@sms_tool_js[0].direction='Start'
set sms_tool_js.@sms_tool_js[0].readport='${port}'
set sms_tool_js.@sms_tool_js[0].sendport='${port}'
set sms_tool_js.@sms_tool_js[0].ussdport='${port}'
set sms_tool_js.@sms_tool_js[0].atport='${port}'

set atsocat.general=atsocat
set atsocat.general.set_port='${port}'


# TODO: fix cellled not found or remove cellled entirely

# set cellled.@device[0]=device
# set cellled.@device[0].data_type='serial'
# set cellled.@device[0].device='${port}'
# set cellled.@device[0].timeout='5'
# set cellled.@device[0].pwm_mode='1'
# set cellled.@device[0].rgb_led='1'
# set cellled.@device[0].red_led='red:signal'
# set cellled.@device[0].green_led='green:signal'
# set cellled.@device[0].blue_led='blue:signal'
# set cellled.@rssi_led[0]=rssi_led
# set cellled.@rssi_led[0].type='bad'
# set cellled.@rssi_led[0].rssi_min='10'
# set cellled.@rssi_led[0].rssi_max='19'
# set cellled.@rssi_led[1]=rssi_led
# set cellled.@rssi_led[1].type='fair'
# set cellled.@rssi_led[1].rssi_min='20'
# set cellled.@rssi_led[1].rssi_max='49'
# set cellled.@rssi_led[2]=rssi_led
# set cellled.@rssi_led[2].type='good'
# set cellled.@rssi_led[2].rssi_min='50'
# set cellled.@rssi_led[2].rssi_max='79'
# set cellled.@rssi_led[3]=rssi_led
# set cellled.@rssi_led[3].type='best'
# set cellled.@rssi_led[3].rssi_min='80'
# set cellled.@rssi_led[3].rssi_max='100'

# TODO! Fixes for LEDs

del system.led_wan

# system.led_5g=led
# system.led_5g.name='5G'
# system.led_5g.sysfs='blue:5g'
# system.led_5g.trigger='default-on'
# system.led_5g.mode='link tx rx'
# system.led_5g.dev='wwan0'
# system.led_wan_port_link=led
# system.led_wan_port_link.name='WAN-PORT-LINK'
# system.led_wan_port_link.sysfs='90000.mdio-1:1c:green:wan'
# system.led_wan_port_link.trigger='netdev'
# system.led_wan_port_link.mode='tx rx link_10 link_100 link_1000 link_2500'
# system.led_wan_port_link.dev='wan'

# uci set system.led_internet=led
# uci set system.led_internet.name='Internet'
# uci set system.led_internet.sysfs='green:internet'
# uci set system.led_internet.trigger='default-on'

# uci set system.led_wifi=led
# uci set system.led_wifi.name='WiFi'
# uci set system.led_wifi.sysfs='green:wifi'
# uci set system.led_wifi.trigger='default-on'

# system.@led[4]=led
# system.@led[4].name='Mobile Signal'
# system.@led[4].sysfs='green:signal'
# system.@led[4].trigger='default-on'

set v2raya.config=v2raya
set v2raya.config.enabled='1'
set v2raya.config.ipv6_support='off'
set v2raya.config.nftables_support='on'
set v2raya.config.log_level='info'
set v2raya.config.log_max_days='3'

set adblock-fast.config.enabled='0'
set adblock-fast.config.compressed_cache='1'
set adblock-fast.config.config_update_enabled='1'
add adblock-fast file_url
set adblock-fast.@file_url[-1].name='📕 Multi ULTIMATE - Aggressive protection'
set adblock-fast.@file_url[-1].url='https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/ultimate.txt'
add adblock-fast file_url
set adblock-fast.@file_url[-1].name='🎉 Pop-Up Ads - Protects against annoying and malicious pop-up ads!'
set adblock-fast.@file_url[-1].url='https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/popupads.txt'
add adblock-fast file_url
set adblock-fast.@file_url[-1].name='🔐 Threat Intelligence Feeds - Increases security significantly!'
set adblock-fast.@file_url[-1].url='https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/tif.txt'
add adblock-fast file_url
set adblock-fast.@file_url[-1].name='🔏 Dynamic DNS blocking - Protects against the malicious use of dynamic DNS services!'
set adblock-fast.@file_url[-1].url='https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/dyndns.txt'
add adblock-fast file_url
set adblock-fast.@file_url[-1].name='💻 Badware Hoster blocking - Protects against the malicious use of free host services!'
set adblock-fast.@file_url[-1].url='https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/hoster.txt'
add adblock-fast file_url
set adblock-fast.@file_url[-1].name='🎰 Gambling - Protects against gambling content!'
set adblock-fast.@file_url[-1].url='https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/dnsmasq/gambling.txt'

EOF

uci changes
uci commit

exit 0
